### ISSUE TITLE
Confused as to what this plugin does

### ISSUE THREAD

**Issue by RichardJECooke** [lhl2617/VSLilyPond-PDF-preview#75]
Hi. I thought this plugin made VS into something like Frescobaldi - when I save my .ly file the plugin will display the PDF in a side window. 
But it seems each time you save you have to convert and open the PDF yourself?  All this plugin does is allow you to click on a section of the PDF and jump to a spot in the code?  Is that right? The documentation doesn't make the purpose clear to me.

**Comment by Apostolique** [comment]
In order to use this, you'll want the follow extensions:

You will want the following extensions:

* [VSLilyPond](https://marketplace.visualstudio.com/items?itemName=lhl2617.VSLilyPond)
* [LilyPond Syntax](https://marketplace.visualstudio.com/items?itemName=jeandeaual.lilypond-syntax)
* [LilyPond AutoComplete (Commands & Keywords)](https://marketplace.visualstudio.com/items?itemName=lhl2617.lilypond-snippets)
* [LilyPond Formatter](https://marketplace.visualstudio.com/items?itemName=lhl2617.lilypond-formatter)
* [LilyPond PDF Preview](https://marketplace.visualstudio.com/items?itemName=lhl2617.lilypond-pdf-preview)

This will give you a development environment similar to Frescobaldi. When you save, the PDF will automatically get regenerated. You'll be able to go back and forth between the code and the PDF. You'll be able to play the midi.

**Comment by RichardJECooke** [comment]
Ohh, I see, once you've opened the PDF in the side window manually it automatically regenerates and refreshes. Thanks!

(All the plugins you listed are installed with VSLilyPond in one click btw).

**Comment by lhl2617** [comment]
> (All the plugins you listed are installed with VSLilyPond in one click btw).
yep :D
